name: Simple CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: 
      name: ENG

    if: vars.ENV1 == 'toto'
    steps:
    - name: Run a one-line script
      run: |
        echo "test de variable OK : " {{ vars.ENV1 }}

